amd64 UEFI loader copy_staging work and msdosfs_rename reports
freebsd/freebsd-quarterly pull request #394
Opened 2021-09-21 17:17 UTC by kostikbel

2021-09-21 17:58 UTC, emaste commented on 2021q3/copy_staging.adoc
> +== Changes to UEFI boot on amd64 staging
I would drop "staging" here, it refers to an aspect of the boot but reads as if this is part of an "amd64 staging" branch.

How about simply "Improved amd64 UEFI boot"?

2021-09-21 17:58 UTC, emaste commented on 2021q3/copy_staging.adoc
> +such requirement is that loader must coordinate its memory use with
One such requirement (no "of")

2021-09-21 17:58 UTC, emaste commented on 2021q3/copy_staging.adoc
> +regions that are reserved by BIOS for different reasons, most knows
... different reasons.
Examples are runtime...

2021-09-21 17:58 UTC, emaste commented on 2021q3/copy_staging.adoc
> +and OS to use. [Of course it is not that straightforward, the
() are typical, (Of course ... workarounds there.)

2021-09-21 17:58 UTC, emaste commented on 2021q3/copy_staging.adoc
> +Also, when preparing to handle the control of to the kernel, loader
Maybe

... preparing to pass control to the kernel, the loader creates...

2021-09-21 17:58 UTC, emaste commented on 2021q3/copy_staging.adoc
> +loader got support for UEFI environment.  Loader prepares kernel and
maybe "loader gained support for the UEFI environment"

2021-09-21 17:58 UTC, emaste commented on 2021q3/copy_staging.adoc
> +auxillary preload data in so called staging area while UEFI boot
in //a// so called staging

2021-09-21 17:58 UTC, emaste commented on 2021q3/copy_staging.adoc
> +outcome was a weird and hard to diagnose boot time failures, typically
"a" doesn't match "failures"
maybe
"hard to diagnose boot time failure, typically a hard hang when the loader started the kernel."

2021-09-21 17:58 UTC, emaste commented on 2021q3/copy_staging.adoc
> +Described work allows UEFI loader on amd64 to start kernel from the
The work described in this report allows
or just
This project allows

2021-09-21 17:58 UTC, emaste commented on 2021q3/copy_staging.adoc
> +all places where amd64 kernel grown a dependency on its physical
grew a dependency
or perhaps
had a dependency

2021-09-21 17:58 UTC, emaste commented on 2021q3/copy_staging.adoc
> +in-place staging are ('non-copying mode').  If needed, this can be
staging //area// I presume?

2021-09-21 17:58 UTC, emaste commented on 2021q3/copy_staging.adoc
> +controlled by loader copy_staging command.  Also, the code to grow
maybe "overridden with the ... command". Perhaps include an inline example if it doesn't make this too awkward.

2021-09-22 02:05 UTC, pauamma commented on 2021q3/msdosfs_rename.adoc
> +rename does not create cyclic parent relations between directories.
I may be overly picky here, but I'd s/cyclic/circular/.

2021-09-22 02:05 UTC, pauamma commented on 2021q3/msdosfs_rename.adoc
> +added to msdosfs and directory path checker changed to non-blocking
s/and/and the/

2021-09-22 02:05 UTC, pauamma commented on 2021q3/msdosfs_rename.adoc
> +Sponsor: The FreeBSD Foundation (kib)
Maybe elaborate what "(kib)" means? Maybe "(work by kib)"?

2021-09-22 02:31 UTC, emaste commented on 2021q3/copy_staging.adoc
> +UEFI BIOS on PC provides much more rich and streamlined environment
streamlined would have to change too then, "a much richer and more streamlined ..."

2021-09-22 02:32 UTC, emaste commented on 2021q3/copy_staging.adoc
> +BIOS, only using memory that was allocated for it.  Even after loader
yeah, I think "the BIOS" here sounds better

2021-09-22 15:02 UTC, emaste commented on 2021q3/copy_staging.adoc
> +creates quite special temporal mappings, where low 1G of physical
"very" seems slightly more typical to me, although for quarterly report entries I think it isn't critical

2021-09-23 01:06 UTC, pauamma commented on 2021q3/msdosfs_rename.adoc
> +rename does not create cicrular parent relations between directories.
s/cicrular/circular/

2021-09-23 01:15 UTC, pauamma commented on 2021q3/copy_staging.adoc
> +such requirement is that loader must coordinate its memory use with
Still needs "the", I think.

2021-09-23 01:15 UTC, pauamma commented on 2021q3/copy_staging.adoc
> +the loader gained support for the UEFI environment.  The oader prepares kernel and
s/The oader/The loader/

2021-09-23 01:15 UTC, pauamma commented on 2021q3/copy_staging.adoc
> +auxiliary preload data in so called staging area while UEFI boot
s/so called/so-called/

Also needs "the" or "a" (not sure which) after "in".

2021-09-23 01:15 UTC, pauamma commented on 2021q3/copy_staging.adoc
> +needed.  But there are issues, the biggest is that memory at 2M might
s/issues,/issues;/ (avoid comma splice)

2021-09-23 01:15 UTC, pauamma commented on 2021q3/copy_staging.adoc
> +The work described in this report allows UEFI loader on amd64 to start
s/UEFI/the UEFI/

2021-09-23 01:47 UTC, pauamma commented on 2021q3/copy_staging.adoc
> +Also, the code to grow staging area was made much more robust,
s/the staging area/staging area/

2021-09-23 01:47 UTC, pauamma commented on 2021q3/copy_staging.adoc
> +does so straight into correct kernel page table, without loading
s/correct/the correct/

2021-09-23 01:47 UTC, pauamma commented on 2021q3/copy_staging.adoc
> +location.  Most complicated part was application processors startup,
s/Most/The most/

2021-09-29 09:33 UTC, pauamma requested changes

2021-09-29 09:33 UTC, pauamma commented on 2021q3/msdosfs_rename.adoc
> +Sponsor: The FreeBSD Foundation (kib' contributions)
s/kib/kib's/ ("not ending in s or z" is the rule, IIRC)

2021-09-29 10:31 UTC, pauamma approved these changes
LGTM.

2021-10-11 21:29 UTC, merged