2021q3 Git entry with input from imp and lwhsu
freebsd/freebsd-quarterly pull request #416
Opened 2021-10-08 14:12 UTC by Jehops

2021-10-08 22:03 UTC, pauamma requested changes

2021-10-08 22:03 UTC, pauamma commented on 2021q3/git.adoc
> +With the end the third quarter of 2021, we are approaching the one-year anniversary of the transition of the doc and src repositories from Subversion to Git.  The 2021Q4 branch of the ports tree has
s/end the/end of the/

2021-10-08 22:03 UTC, pauamma commented on 2021q3/git.adoc
> +Remaining work includes continuing with refinements to Git documentation in the Handbook, committing new and updated repository hooks for managing branch content and commit mail, and surveying pre-co
s/will begin/will be/

2021-10-09 20:32 UTC, pauamma approved these changes
LGTM now.

2021-10-11 12:01 UTC, Jehops commented
No, you're not missing anything. I didn't mean to click the link.

2021-10-11 21:20 UTC, merged