Add 2021q3 Azure report
freebsd/freebsd-quarterly pull request #423
Opened 2021-10-15 00:07 UTC by lwhsu

2021-10-15 03:53 UTC, pauamma requested changes

2021-10-15 03:53 UTC, pauamma commented on 2021q3/azure.adoc
> +The changes for building official images on Azure Marketplace, which fulfill the requirements of Azure and FreeBSD cloud images like disk layout and UEFI for Gen2 VM, along with some minor improvemen
"The changes ... has  been ..." <--- number agreement.

2021-10-15 03:53 UTC, pauamma commented on 2021q3/azure.adoc
> +Microsoft Azure Network Adapter (MANA) is the new network adapter from Microsoft which will be available in Azure public cloud.
s/in Azure/in the Azure/

2021-10-15 03:53 UTC, pauamma commented on 2021q3/azure.adoc
> +It provides SRIOV NIC as virtual function to guest OS running on Hyper-V.
s/as virtual function to guest/as a virtual function to a guest/ (also, should "function" be "driver" here?

2021-10-18 11:49 UTC, debdrup commented
I've merged this, thank you for the report entry. :)

2021-10-18 11:49 UTC, closed without merging