2021q4: add lldb report
freebsd/freebsd-quarterly pull request #432
Opened 2021-12-21 13:06 UTC by mgorny

CC @krytarowski, @emaste

2021-12-26 01:34 UTC, pauamma requested changes
LGTM (unless I missed something) other than that.

2021-12-26 01:34 UTC, pauamma commented on 2021q4/lldb.adoc
> +The support for FreeBSD vmcores has also been added to LLDB.  This makes it
s/The support/Support/

2021-12-26 01:34 UTC, pauamma commented on 2021q4/lldb.adoc
> +server over the serial port, and LLDB server gained support for accepting
"a serial port" and "the LLDB server", I think.

2021-12-26 01:34 UTC, pauamma commented on 2021q4/lldb.adoc
> +communication over the serial port.  This opened the possibility of using
"a serial port", as above.

2021-12-26 08:05 UTC, mgorny commented
Thanks. English is really hard, let's write in Esperanto the next quarter ;-).

2021-12-28 02:40 UTC, pauamma approved these changes
LGTM now.

2022-01-10 00:43 UTC, merged