add portconfig.adoc
freebsd/freebsd-quarterly pull request #452
Opened 2022-03-21 20:46 UTC by alfonsosiciliano

Add entry for PortConfig (portconfig.adoc)

2022-03-21 20:47 UTC, alfonsosiciliano commented
CC @bapt

2022-03-22 00:04 UTC, pauamma requested changes

2022-03-22 00:04 UTC, pauamma commented on 2022q1/PortConfig
> +theme, borders, and so on, each feature is documented inside the manual.
s/and so on,/and so on;/

2022-03-22 00:04 UTC, pauamma commented on 2022q1/PortConfig
> +PortConfig for each use, please report any problem.
s/,/;/

2022-03-22 07:34 UTC, alfonsosiciliano commented on 2022q1/PortConfig
> +PortConfig for each use, please report any problem.
fixed

2022-03-22 07:34 UTC, alfonsosiciliano commented on 2022q1/PortConfig
> +theme, borders, and so on, each feature is documented inside the manual.
fixed

2022-03-22 07:34 UTC, alfonsosiciliano commented on 2022q1/PortConfig
> +As each terminal has different properties PortConfig can be custimized via
fxed

2022-03-22 07:35 UTC, alfonsosiciliano commented on 2022q1/PortConfig
> +performs this task, unfortunately it depends on non-permissive software.
fixed

2022-03-22 07:35 UTC, alfonsosiciliano commented on 2022q1/PortConfig
> +it and its dependecies (libbsddialog and libncurses) are released completely
fixed

2022-03-22 07:35 UTC, alfonsosiciliano commented on 2022q1/PortConfig
> +PortConfig is an utility for setting the port options via a Text User Interface,
OK "."

2022-03-22 07:35 UTC, alfonsosiciliano commented on 2022q1/PortConfig
> +It is possible to configure a port before the building and installation,
OK "."

2022-03-22 07:35 UTC, alfonsosiciliano commented on 2022q1/PortConfig
> +administrators to install applications.
OK

2022-03-22 07:35 UTC, alfonsosiciliano commented
Fixed

2022-03-22 13:32 UTC, bapt commented
LGTM

2022-03-22 19:01 UTC, pauamma approved these changes

2022-03-25 10:42 UTC, pauamma approved these changes

2022-04-01 20:29 UTC, pauamma approved these changes

2022-04-02 00:50 UTC, merged