Office 2022q1 report
freebsd/freebsd-quarterly pull request #463
Opened 2022-03-31 22:37 UTC by fluffykhv

2022-04-01 19:29 UTC, pauamma requested changes
Can you redo this without the upstream merge? See https://github.com/freebsd/freebsd-quarterly/pull/455#issuecomment-1078747188 for the suggested workflow.

2022-04-01 19:29 UTC, pauamma commented on 2022q1/office.adoc
> +During the 2022Q1 period we are pushed maintenance patches for LibreOffice 7.2 leaf to the quarterly branch and bring the latest, 7.3, releases
s/are pushed/pushed/

2022-04-07 17:18 UTC, lwhsu commented
I fixed the grammar and did some updates. A new PR created https://github.com/freebsd/freebsd-quarterly/pull/465 for workflow issue.

2022-04-08 23:20 UTC, pauamma commented
Closing in favor of #465 as all changes requested here are present there. Thanks.

2022-04-08 23:20 UTC, closed without merging