Semihalf updates
freebsd/freebsd-quarterly pull request #479
Opened 2022-06-27 14:38 UTC by semihalf-wojtas-marcin

Hi,

Please check Semihalf Team updates from the 2022Q2.

Best regards,
Marcin

2022-06-27 20:43 UTC, pauamma requested changes

2022-06-29 18:39 UTC, semihalf-wojtas-marcin commented on 2022q2/ena.adoc
> +  * Fix for the retrieval of the ENI metrics.
Done.

2022-06-29 18:39 UTC, semihalf-wojtas-marcin commented on 2022q2/ena.adoc
> +  * Improvement for the reset routine handling,
Done.

2022-06-29 18:39 UTC, semihalf-wojtas-marcin commented on 2022q2/ena.adoc
> +* Upstream of the ENA driver v2.5.0, which was including:
Done.

2022-06-29 18:39 UTC, semihalf-wojtas-marcin commented on 2022q2/shp_rand.adoc
> +The feature planned to be turned on by default for 64bit binaries, across all architectures.
Done.

2022-07-02 03:35 UTC, pauamma approved these changes

2022-07-09 00:27 UTC, merged