portmgr.adoc: fixes for AsciiDoc
freebsd/freebsd-quarterly pull request #490
Opened 2022-07-16 00:46 UTC by grahamperrin

It seems that the first line in a list must be **non-consecutive** to the previous line of text. 

In other words: blank lines are required.

2022-07-16 01:21 UTC, grahamperrin commented
FreeBSD bug [265246 – AsciiDoctor primer: make AsciiDoc examples of lists less ambiguous](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265246)

2022-07-17 14:28 UTC, pauamma reviewed
Leaning toward no, but I'd like a second opinion on this one. It's been "Collection" at least as far back as 2020q1.

2022-07-17 14:30 UTC, pauamma requested changes

2022-07-17 14:30 UTC, pauamma commented on 2022q2/portmgr.adoc
> +FreshPorts tells us the number of ports grew to over 50,000, a new milestone.
Won't apply. I removed Freshports and corrected to 30K meanwhile.

2022-07-17 14:39 UTC, pauamma requested changes
I'm unsure about this specific commit. Second opinion, please. (So better hold back on changes I requested here until that comes.)

2022-07-17 14:39 UTC, pauamma commented on 2022q2/portmgr.adoc
> +FreshPorts tells us that the number of ports grew to over 50,000, a new milestone.
Won't apply, Freshports mention removed.

2022-07-17 14:39 UTC, pauamma commented on 2022q2/portmgr.adoc
> +The Ports Tree grew by seven percent, a slight decrease in commit activity and a constant number of PRs.
Same as above.

2022-07-17 14:39 UTC, pauamma commented on 2022q2/portmgr.adoc
> +portmgr welcomed back salvadore@ but also said goodbye to seven ports committers due to lack of activity.
Starts with lowercase letter.

2022-08-02 23:48 UTC, lsalvadore commented
@grahamperrin: The quarterly team is now in the process of putting reports together for pubblication. Is this pull request still relevant? If it is, could you please update it so we can merge it? If it is not, can we close it?

Thanks.

2022-08-08 14:19 UTC, lsalvadore commented
@grahamperrin: After 22 days of inactivity on this pull request, I am going to close it at least for now and proceed with report pubblication process. If there is something that you still want to merge, please reopen the pull request or open a new one.

2022-08-08 14:19 UTC, closed without merging

2022-08-13 19:47 UTC, grahamperrin commented
Sorry for the lateness here, priorities were elsewhere.