Add 2022q2 CI report
freebsd/freebsd-quarterly pull request #493
Opened 2022-07-18 22:09 UTC by lwhsu

2022-07-22 20:24 UTC, pauamma requested changes

2022-07-22 20:24 UTC, pauamma commented on 2022q2/ci.adoc
> +* Organize the scripts in freebsd-ci repository for preparing to merge to src repository
"Organizing" for consistency with other bullet points.
s/for preparing to merge/to prepare for merging/ (reads less stilted to me)
"in the ... repository" x 2 (taste)

2022-07-22 20:24 UTC, pauamma commented on 2022q2/ci.adoc
> +* Update documents on wiki
s/Update/Updating/

2022-07-22 20:24 UTC, pauamma commented on 2022q2/ci.adoc
> +* Collecting and sorting CI tasks and ideas link:https://hackmd.io/@FreeBSD-CI/freebsd-ci-todo[here]
\* link:https://hackmd.io/@FreeBSD-CI/freebsd-ci-todo[Collecting and sorting CI tasks and ideas]

Rationale: https://webaim.org/resources/quickref/#links

2022-07-22 20:24 UTC, pauamma commented on 2022q2/ci.adoc
> +* Implementing using bare metal hardware to run test suites
s/using bare metal hardware/use of bare-metal hardware/

2022-07-22 20:24 UTC, pauamma commented on 2022q2/ci.adoc
> +* Improving maturity of the hardware lab and adding more hardware under test
By "hardware under test", do you mean "hardware for testing"?

2022-07-28 16:15 UTC, lwhsu commented
Please feel free to modify more before merging. Thanks!

2022-07-29 10:46 UTC, merged