2022q3/calendar-data.adoc: Add report
freebsd/freebsd-quarterly pull request #500
Opened 2022-09-20 11:08 UTC by lsalvadore

@se, @bsdimp: I am adding a report to our 2022q3 quarterly status report to inform all quarterly status reports readers about the license added to calendar-data. Please feel free to suggest improvements if you want.

2022-09-20 20:23 UTC, bsdimp commented
looks good to me.

2022-09-22 02:07 UTC, pauamma requested changes

2022-09-22 20:44 UTC, lsalvadore commented on 2022q3/calendar-data.adoc
> +About two years ago, the calendar files in the base repository where removed from there and a new link:https://github.com/freebsd/calendar-data[repository] was created on GitHub; see also this link:h
I prefer the original version of the text, but I have fixed the typo, removed the redundant link and made the other link more informative.

Thank you very much for your review.

2022-09-23 03:06 UTC, pauamma approved these changes

2022-09-26 01:46 UTC, merged