[sysutils/lsof] major update
freebsd/freebsd-quarterly pull request #504
Opened 2022-09-24 15:45 UTC by lrosenman

Status report for sysutils/lsof

2022-09-24 23:46 UTC, pauamma requested changes

2022-09-24 23:46 UTC, pauamma commented on lsof.adoc
> +in /dev/kmem for data and using userspace API's.  This has taken a long
```suggestion
in /dev/kmem for data and using the userland API.  This has taken a long
```
Single API, comprising a bunch of system calls, device data formats, etc. Or if you see it as a file IO API, a process control API, a resource allocation API, etc., that is one API per functional group, I'd still remove the ': APIs.

2022-09-24 23:46 UTC, pauamma commented on lsof.adoc
> +github PR to https://github.com/lsof-org/lsof.
If there's a way to find out about changes breaking lsof, best to mention it here, I think.

2022-09-24 23:46 UTC, pauamma commented on lsof.adoc
> +
Spurious extra linebreaks.

2022-09-25 00:28 UTC, lrosenman commented
I believe I have resolved all the comments

2022-09-25 02:03 UTC, pauamma approved these changes
Yep, LGTM now.

2022-09-26 01:47 UTC, merged