pot/potluck status update
freebsd/freebsd-quarterly pull request #511
Opened 2022-09-30 08:52 UTC by hny-gd

2022-10-01 00:29 UTC, pauamma requested changes

2022-10-02 16:35 UTC, hny-gd commented on 2022q3/pot.adoc
> +During the last quarter, link:https://github.com/bsdpot/pot/releases/tag/0.15.3[pot 0.15.3] was released. It contains a number of improvements like mount-out, signal and exec commands, better jail li
Added in the new commit and added comma.

2022-10-02 16:35 UTC, hny-gd commented on 2022q3/pot.adoc
> +Potluck aims to be to FreeBSD and pot what Dockerhub is to Linux and Docker: a repository of pot flavours and complete container images for usage with pot and in many cases nomad.
Fixed ("Nomad")

2022-10-02 16:36 UTC, hny-gd commented on 2022q3/pot.adoc
> +Since the last status report, link:https://github.com/bsdpot/potluck/commits/master[many changes] have been committed, including many fixes and improvements to core images like link:https://github.co
Changed.

2022-10-07 22:36 UTC, pauamma approved these changes
Needs commas around the nomad-pot link text, but that's minor, so I'll do it while merging.

2022-10-08 03:21 UTC, merged