Add xfce status report.
freebsd/freebsd-quarterly pull request #545
Opened 2022-12-16 15:24 UTC by madpilot78

2022-12-17 11:06 UTC, pauamma requested changes
Some (like the link syntax) are mechanical and I could make them while or after merging,  but others are best left to your appreciation.

2022-12-18 14:26 UTC, madpilot78 commented on 2022q4/xfce.md
> +environment, with many improvements in the Thunar file manager.
Thanks, should have reread it before submitting!

2022-12-18 14:29 UTC, madpilot78 commented on 2022q4/xfce.md
> +Also various upstream releases now include patches that were present in
To tell the truth I was using "release" a a substantive.

But there is no problem changing that.

2022-12-18 16:32 UTC, pauamma approved these changes
Minor nit, fixable while/after merging.

2022-12-18 16:32 UTC, pauamma commented on 2022q4/xfce.md
> +link:https://www.freshports.org/x11-wm/xfce4[Xfce meta-port on FreshPorts] URL: link:https://www.freshports.org/x11-wm/xfce4[link:https://www.freshports.org/x11-wm/xfce4]
```suggestion
link:https://www.freshports.org/x11-wm/xfce4[Xfce meta-port on FreshPorts] URL: link:https://www.freshports.org/x11-wm/xfce4[https://www.freshports.org/x11-wm/xfce4]
```

2022-12-18 16:33 UTC, madpilot78 commented on 2022q4/xfce.md
> +link:https://www.freshports.org/x11-wm/xfce4[Xfce meta-port on FreshPorts] URL: link:https://www.freshports.org/x11-wm/xfce4[link:https://www.freshports.org/x11-wm/xfce4]
Thanks!

2022-12-18 19:43 UTC, pauamma approved these changes

2022-12-21 18:46 UTC, merged