Add 2022q4 OpenStack on FreeBSD project update
freebsd/freebsd-quarterly pull request #557
Opened 2022-12-31 13:29 UTC by starbops

2022-12-31 21:35 UTC, grahamperrin commented on 2022q4/openstack-on-freebsd.adoc
> +And for neutron, it is the `openvswitch` mechanism driver.
For neutron, …

2022-12-31 21:35 UTC, grahamperrin commented on 2022q4/openstack-on-freebsd.adoc
> +In the next few weeks, we will focus on breaking through the last mile of the instance spawn path and wrapping up the documentation regarding POC site construction. We will also try rebasing the port
In the first few weeks of 2023, …

2022-12-31 22:33 UTC, pauamma requested changes

2022-12-31 22:33 UTC, pauamma commented on 2022q4/openstack-on-freebsd.adoc
> +The step-by-step documents constructing a POC can be found link:https://github.com/openstack-on-freebsd/docs[here].
s/constructing/for constructing/
s/here/in the `docs` repository/

2022-12-31 22:33 UTC, pauamma commented on 2022q4/openstack-on-freebsd.adoc
> +Concerning legitimate porting, there are three significant TODOs:
s/legitimate/actual/ maybe? Not sure what you mean here.

2022-12-31 22:33 UTC, pauamma commented on 2022q4/openstack-on-freebsd.adoc
> +People interested in helping with the project can first help verify the documentation by following the installation guide.
s/verify/check/, I think.

2023-01-01 04:44 UTC, starbops commented on 2022q4/openstack-on-freebsd.adoc
> +Concerning legitimate porting, there are three significant TODOs:
I want to convey that there's more work to tidy things up since the current porting is more like a workaround/hack. I'm not sure if the word "actual" here is suitable. Maybe there's better wording?

2023-01-01 22:18 UTC, pauamma commented on 2022q4/openstack-on-freebsd.adoc
> +Concerning legitimate porting, there are three significant TODOs:
"better"? "more robust"? "complete"?

2023-01-02 04:44 UTC, grahamperrin commented on 2022q4/openstack-on-freebsd.adoc
> +It indicates we still have lots of work to undertake to make the changes back to OpenStack upstream.
> It indicates we still have …

With four sentences preceding the word 'It', the meaning of it is unclear. 

Instead, maybe: 

> We still have …

2023-01-02 04:44 UTC, grahamperrin commented on 2022q4/openstack-on-freebsd.adoc
> +Concerning legitimate porting, there are three significant TODOs:
The subsequent bullet points are fairly self-explanatory. 

The first of the three points uses the word _proper_, so it's understood that the current approach is _less than_ proper (a workaround, a hack). 

> Concerning legitimate porting, there are three significant TODOs:

Instead: 

> TODOs include:

2023-01-02 15:44 UTC, starbops commented on 2022q4/openstack-on-freebsd.adoc
> +Concerning legitimate porting, there are three significant TODOs:
Updated. Thanks for the advice.

2023-01-02 15:50 UTC, grahamperrin approved these changes

2023-01-02 15:51 UTC, grahamperrin approved these changes

2023-01-03 17:45 UTC, pauamma approved these changes
Look good so far. Let me know when you make it final.

2023-01-04 15:06 UTC, starbops commented
> Look good so far. Let me know when you make it final.

@pauamma I thinks it’s ready now, thanks!

2023-01-06 00:20 UTC, merged