Add quarterly report for re@
freebsd/freebsd-quarterly pull request #560
Opened 2023-01-01 00:31 UTC by cperciva

2023-01-01 18:09 UTC, pauamma approved these changes

2023-01-02 05:12 UTC, grahamperrin requested changes
Singular, not plural, for one BETA. 

Whilst here: conciseness.

2023-01-02 05:12 UTC, grahamperrin commented on 2022q4/releng.adoc
> +During the fourth quarter of 2022, the Release Engineering Team continued providing weekly development snapshot builds for the *main*, *stable/13*, and *stable/12* branches.
> During the fourth quarter of 2022, the Release Engineering Team

The previous paragraph began with the same phrase, and it's all in the context of a quarterly report for the specified period. 

Instead: 

> The Team

2023-01-02 05:12 UTC, grahamperrin commented on 2022q4/releng.adoc
> +The FreeBSD Release Engineering Team is responsible for setting and publishing release schedules for official project releases of FreeBSD, announcing code freezes and maintaining the respective branc
Instead: 

> Team responsibilities include setting and publishing release schedules, announcing code freezes and maintaining branches.

2023-01-02 05:12 UTC, grahamperrin commented on 2022q4/releng.adoc
> +During the fourth quarter of 2022, the Release Engineering Team completed work on the 12.4-RELEASE cycle.
> the Release Engineering Team completed

Instead: 

> the Team completed

2023-01-02 05:12 UTC, grahamperrin commented on 2022q4/releng.adoc
> +In the first quarter of 2023, the Release Engineering Team will start work on the upcoming 13.2-RELEASE.
> the Release Engineering Team will

Instead: 

> the Team will

2023-01-02 05:12 UTC, grahamperrin commented on 2022q4/releng.adoc
> +In the first quarter of 2023, the Release Engineering Team will start work on the upcoming 13.2-RELEASE.
> work on the upcoming 13.2-RELEASE.

Instead: 

> work on 13.2-RELEASE.

2023-01-02 07:33 UTC, cperciva commented on 2022q4/releng.adoc
> +During the release cycle, only one BETA builds and two RC (release candidate) builds were needed; overall the release cycle went very smoothly and the release took place on December 5th.
Fixed.

2023-01-02 07:35 UTC, cperciva commented
Thanks for the suggestions re conciseness; but I was reusing text which appeared in previous releng reports and I'd prefer not to change the template at this time.

2023-01-02 09:36 UTC, grahamperrin commented
@cperciva thanks, understood.

2023-01-03 18:23 UTC, pauamma approved these changes

2023-01-06 00:23 UTC, merged