Add 2022q4 Azure report.
freebsd/freebsd-quarterly pull request #577
Opened 2023-01-12 18:07 UTC by lwhsu

2023-01-13 20:44 UTC, pauamma requested changes

2023-01-13 20:44 UTC, pauamma commented on 2022q4/azure.adoc
> +link:https://wiki.freebsd.org/HyperV[Microsoft HyperV article on FreeBSD wiki] URL: link:https://wiki.freebsd.org/HyperV[]
`URL: link:https://wiki.freebsd.org/MicrosoftAzure[https://wiki.freebsd.org/MicrosoftAzure]` and likewise for the next one.

2023-01-13 20:44 UTC, pauamma commented on 2022q4/azure.adoc
> +** All the requirted codes are merged to main branch, and can create ZFS-bared image by specifying `VMFS=zfs`.
s/requirted/required/

What does "ZFS-bared" mean?

s/image/images/, I think.

2023-01-13 20:44 UTC, pauamma commented on 2022q4/azure.adoc
> +** Need to make the build process more automaitc and collaborating with release engineering to start generating snapshots.
s/automaitc/automatic/

2023-01-13 20:44 UTC, pauamma commented on 2022q4/azure.adoc
> +* Update FreeBSD related doc at link:https://docs.microsoft.com[]
`link:https://docs.microsoft.com[https://docs.microsoft.com]` (or more explicit link if there's a specific subdir for FreeBSD)

2023-01-14 06:56 UTC, lwhsu commented
I think repeat the same URL in the square brackets isn't very useful, and may even cause some editing error in the future.  Just using the `link:` macro and `[]` to explicitly mark the URL part should be enough for all the cases, including the special characters.

Also, I just found that this seems what other files do.  I am OK to add to this one, but I strongly suggest let's remove to a simpler syntax, in this, or at least the next quarter.

2023-01-14 08:46 UTC, grahamperrin commented
> … repeat the same URL in the square brackets …

If I understand correctly, the repetition is currently to _add links to the mail version_: 

* https://github.com/freebsd/freebsd-quarterly/issues/530#issuecomment-1278250578

2023-01-14 08:49 UTC, grahamperrin commented
From <https://github.com/freebsd/freebsd-quarterly#readme>, with emphasis: 

> … please, **do not squash or force-push** …

2023-01-14 12:12 UTC, pauamma approved these changes
NTS: fill in empty []s.

2023-01-14 12:27 UTC, merged

2023-01-14 21:31 UTC, lwhsu commented
> From https://github.com/freebsd/freebsd-quarterly#readme, with emphasis:
> 
> > … please, **do not squash or force-push** …

Apologies, didn't notice this policy change. BTW, force-push on feature branch is quite common and useful to keep the history (of the main branch) clean, this is widely used in many other pleases.  Also the review feature of GitHub is improved to cope with it.  Please seriously consider this.

cc @lsalvadore

2023-01-14 23:50 UTC, lsalvadore commented
The reviewing procces is mainly in @pauamma's and @grahamperrin's hands, so I think they should choose what works best for them about squashing and force-pushing. Personally, I have no preference.

A few thoughts about the topic:

- starting from the next quarter, if everything  goes as planned, authors will be able to submit their reports on Phabricator too. Things such as squashing and force-pushing are not part of the usual Phabricator workflow: authors will submit their work, modify their files following the reviewing process and only one single commit to the docs repository will end the review. Further changes will require more commits and could not be squashed in the past commits;

- if one wants a cleaner history in the main project, it is not necessary to force-push anything in pull requests: it is enough to select the "Squash and merge" option in GitHub when merging the pull request and only one commit will result. And using git from command line allows for even more flexibility (and then GitHub might not automatically recognize the pull request merging: this often happens to me. Not a big deal). However I also understand that some report authors might prefer to keep a clean history with multiple commits, which would require to force-push.

- policies are useful and important, but they also need to be applied with care for special cases. See for example my recent pull request #562: I only had to fix a typo in a commit message, without modifying any file. It would have been absurd to merge the pull request including the commit message with the typo instead of amending it and force-pushing;

- attempting to keep a clean history is nice, but is also difficult. Indeed, what happens in pull requests is only the first main reviewing process, but later the reports are reviewed again. I review them once again when I put them together and render them, correcting a few things here and there as needed (mostly adoc syntax and typos). Then they can be reviewed again when I open the Phabricator review to commit the changes to the docs repository. And the final review is done by our readers, who are often able to spot a few more things after publication in spite of our best efforts. Thus, many reports happen to get more than one commit even if they were created with only one clean single commit pull request;

- I think we all agree that a cleaner history is better. However, we should not forget that if we use a VCS it is also to keep track of who does what and why. And also to change our mind if we want to. Cleaning history risks to go against these goals.

2023-01-15 20:01 UTC, grahamperrin commented
Thanks, all

> … choose what works best for them about squashing and force-pushing. 

I'm aware of the plea in https://github.com/freebsd/freebsd-quarterly/blob/main/README.adoc only because I helped to edit the file. 

> Personally, I have no preference. …

I don't know enough about Git to express a preference. 

If someone can point me to a case where a squash or force-push _did_ cause difficulty, I might form a preference …